files:
  financial_history: banksuite_financials_last_3y_full.parquet
  locations: Locations__Bank_Suite_.csv
  institutions: Institutions__Bank_Suite_.csv

identifiers:
  bank_id: RSSDID
  institution_rssd: FED_RSSD
  cert: CERT

names:
  land_name: NAMEFULL
  institution_name: NAME_inst

dates:
  land_report_date: REPDTE
  institution_report_date: REPDTE
  institution_run_date: RUNDATE
  location_run_date: RUNDATE

financial:
  total_assets: ASSET
  total_deposits: DEP
  total_loans: LNLSNET
  loan_to_deposit_ratio: LOAN_TO_DEPOSIT_RATIO
  asset_growth_cagr_5y: ASSET_GROWTH_CAGR_5Y
  core_deposits_per_fte: COREDEP
  asset_size_bucket: ASSET_SIZE_BUCKET

lending_profile:
  cre:
    - Lending_Profile_CRE_Pct
    - Lending_Profile_CRE_Amt
  ci:
    - Lending_Profile_Industrial_Pct
    - Lending_Profile_Industrial_Amt
    - LNCI
  residential_mortgage:
    - LNRERES
    - LNRERES2
    - LNRERES5
  consumer:
    - Lending_Profile_Other_Pct
    - Lending_Profile_Other_Amt
    - LNCONOTH
    - LNCRCD
    - LNAUTO
  agricultural:
    - Lending_Profile_Agricultural_Pct
    - Lending_Profile_Agricultural_Amt
    - LNAG
  construction:
    - LNRECON2
    - LNRECON5
    - LNRECONS

deposit_mix:
  retail:
    - COREDEP
  business:
    - DEPNIDOM
    - DEPNI

institutional:
  charter_type: CHARTER
  holding_company_rssd: RSSDHCR
  specialty_group: SPECGRPN
  bank_class: BKCLASS

geography:
  market_code: CBSA_NO
  latitude: LATITUDE
  longitude: LONGITUDE
